# Generated by Django 6.0.1 on 2026-01-09 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaLeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('QUERO_LER', 'Quero Ler'), ('LENDO', 'Lendo'), ('LIDO', 'Lido')], default='QUERO_LER', max_length=20)),
                ('nota', models.IntegerField(blank=True, null=True)),
                ('favorito', models.BooleanField(default=False)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leitores', to='books.livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minha_lista', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
