# Generated by Django 6.0.1 on 2026-01-10 14:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('lists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listaleitura',
            options={'verbose_name': 'Item da Lista', 'verbose_name_plural': 'Itens da Lista'},
        ),
        migrations.AlterUniqueTogether(
            name='listaleitura',
            unique_together={('usuario', 'livro')},
        ),
    ]
